### ISSUE TITLE
GPG verification error

### ISSUE THREAD

**Issue by maxel** [sous-chefs/rvm#278]
Hello,

I thought I'd report an issue that seems to have been introduced by the latest RVM release. This release has a new check using GPG to verify validity of the downloaded RVM installer. The problem I'm seeing is when the RVM installer is executed via this cookbook, GPG does not successfully find the default keyring (in the user's home directory) and instead searches in /.gnupg. 

```
gpg: DBG: fd_cache_open (/.gnupg/pubring.gpg) not cached
gpg: DBG: iobuf-3.0: open `/.gnupg/pubring.gpg' fd=7
gpg: DBG: iobuf-3.0: underflow: req=8192
gpg: DBG: iobuf-3.0: underflow: got=0 rc=-1
gpg: DBG: /.gnupg/pubring.gpg: close fd 7
```

It defaults to this location because HOME env is not set. This issue causes gpg verification to fail, which in turn causes our chef-clients to fail.

I wasn't sure where to post, I thought this repo would be a good start.

Thanks.

**Comment by lemattma** [comment]
Here's what I did for user installs:

```ruby
gnupg_dir       = "/home/#{node[:user][:name]}/.gnupg"
gnupg_dir_user  = "chown -R #{node[:user][:name]}:#{node[:user][:group]} #{gnupg_dir};"
gnupg_dir_root  = "if [ -d #{gnupg_dir} ]; then chown -R root:root #{gnupg_dir}; fi;"
gnupg_cmd       = "`which gpg2 || which gpg` --keyserver hkp://keys.gnupg.net --recv-keys #{node['rvm']['gpg_key']};"

execute "Adding gpg key to #{node[:user][:name]}" do
  environment ({"HOME" => "/home/#{node[:user][:name]}"})
  command "#{gnupg_dir_root} #{gnupg_cmd} #{gnupg_dir_user}"
  not_if { node['rvm']['gpg_key'].empty? }
  returns 0
end

include_recipe "rvm::user"
```

It works, but I guess it could be improved.

Martin

**Comment by alambike** [comment]
I'm in ubuntu 14.04 with chef 12 and **rvm::system** fails:
```
           Expected process to exit with [0], but received '2'
           ---- Begin output of bash /tmp/kitchen/cache/rvm-installer-root stable ----
           STDOUT: Downloading https://github.com/wayneeseguin/rvm/archive/1.26.9.tar.gz
           Downloading https://github.com/wayneeseguin/rvm/releases/download/1.26.9/1.26.9.tar.gz.asc
           Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
           Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).
           
           GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.26.9.tgz' - 'https://github.com/wayneeseguin/rvm/releases/download/1.26.9/1.26.9.tar.gz.asc'!
           try downloading the signatures:
           
               sudo gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
           
           or if it fails:
           
               command curl -sSL https://rvm.io/mpapis.asc | sudo gpg --import -
           
           the key can be compared with:
           
               https://rvm.io/mpapis.asc
               https://keybase.io/mpapis
           STDERR: gpg: directory `/root/.gnupg' created
           gpg: new configuration file `/root/.gnupg/gpg.conf' created
           gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
           gpg: keyring `/root/.gnupg/pubring.gpg' created
           gpg: Signature made Wed 07 Jan 2015 11:55:10 AM UTC using RSA key ID BF04FF17
           gpg: Can't check signature: public key not found
           ---- End output of bash /tmp/kitchen/cache/rvm-installer-root stable ----

```

**Comment by alambike** [comment]
Fixed with PR #293. 
The problem comes because I am launching convergence with test-kitchen, and chef run is launched with sudo, so HOME var keeps as '/home/kitchen' and key was added to kitchen user keyring, nor to root.

**Comment by delner** [comment]
I see the pull request added PGP for system install, but what about user install? I'm still getting the "GPG signature verfication failed" when I use `rvm::user` to install. Any ideas?

**Comment by neurogenesis** [comment]
@martinisoft ... any update on the gpg issue and merging fixes into a new release?

**Comment by martinisoft** [comment]
@neurogenesis as far as I know this should be merged in master, but it did not get back ported to the 0.9.x series of releases.
